### ISSUE TITLE
Missing good description and usage 

### ISSUE THREAD

**Issue by ewoks** [in28minutes/TDDin28Minutes#1]
Hi,

would be good if there is some better description what is actually in this repo, how to use it, is there some complement blog post / video to support and describe specific steps etc.. 

Hope you will find time to write some of this soon. Cheers

**Comment by in28minutes** [comment]
Hey.. Thanks for pointing out. I have added in a video tutorial. https://www.youtube.com/watch?v=QXo8bCv1BiQ
